// resource.h - sample for MFC-like app (only numeric defines to match the cleaner regex)
#pragma once

// ==== Auto-generated by ResourceHeaderTool ====
#define IDC_BTN_OK       1
#define IDC_SAMPLEAPP    2
#define IDC_STATIC_TEXT  3
#define IDD_ABOUTBOX     4
#define IDD_MAIN_DIALOG  5
#define IDI_APPICON      6
#define IDM_ABOUT        7
#define IDM_EXIT         8
#define IDR_ACCEL        9
#define IDR_MAINMENU     10
#define IDS_APP_TITLE    11
#define IDS_HELLO        12
// ==== End of auto-generated block ====

// Unused items (should be removed by the tool)
